# OBJS = main.cpp

# CC = g++

# COMPILER_FLAGS = -w

# LINKER_FLAGS = -lSDL2 -lSDL2_image -lSDL2_gfx

# OBJ_NAME  = out

# all: $(OBJS)
# 	$(CC) $(COMPILER_FLAGS) $(OBJS) $(LINKER_FLAGS) -o $(OBJ_NAME)

all:
	python3 pymake.py